apiVersion: adaptdl.petuum.com/v1
kind: AdaptDLJob
metadata:
  generateName: cifar10-
spec:
        # placement: ["phortx1","phortx2", "phortx3"] 
  placement: ["phortx3"] 
  template:
    spec:
      containers:
      - name: main
        command:
        - python3
        - /root/cifar10/main.py
        - --model=ResNet18
        env:
        - name: PYTHONUNBUFFERED
          value: "true"
        resources:
          limits:
            nvidia.com/gpu: 1
            cpu: 8
            memory: "40G"
          requests:
            nvidia.com/gpu: 1
            cpu: 8
            memory: "40G"
        volumeMounts:
        - name: data
          mountPath: /mnt
          readOnly: true
      volumes:
      - name: data
        hostPath:
          path: /mnt
          type: Directory
      imagePullSecrets:
      - name: regcred
        # hostIPC: true
        # hostNetwork: true
